spring.application.name=campusflow-backend
server.port=8080
spring.mongodb.uri=mongodb://localhost:27017/campusflow
spring.data.mongodb.auto-index-creation=true
campusflow.jwt.secret=CampusFlow-Secret-Key-Change-In-Production-At-Least-32-Characters-Long
campusflow.jwt.expiration=86400000
